# Generated by Django 4.0.2 on 2023-08-11 05:55

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile_bio_profile_created_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path, verbose_name='picture'),
        ),
    ]
