# Generated by Django 4.0.2 on 2023-08-24 11:02

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_likes'),
        ('userauths', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path, verbose_name='image'),
        ),
    ]
